### ISSUE TITLE
Patch existing resources(Object)

### ISSUE THREAD

**Issue by cdenneen** [crossplane-contrib/provider-kubernetes#26] opened 2022-02-11 22:37 UTC
Using `provider-aws` to create an EKS cluster and in a composition would be nice to use this provider to "patch" the `aws-auth` configMap with additional mapRoles or mapUsers.

Not sure if this should be implemented here or in `provider-aws`.

**Comment by morningspace** [comment] 2022-02-16 03:51
@cdenneen I think this feature should be available once PR #21 is merged. I'd hope this will be a general way that covers many cases, not just `provider-aws`.

**Comment by morningspace** [comment] 2022-02-24 00:00
@cdenneen Since PR #21 has been merged, can you check if the issue is resolved? I need spend a bit more time to update the docs, but there are some samples at: https://github.com/crossplane-contrib/provider-kubernetes/tree/main/examples/object/references, which is straightforward, and you can take that as reference.

**Comment by morningspace** [comment] 2022-02-24 00:04
With that, I'm going to close it and feel free to reopen if there's issue.

**Closed by morningspace** 2022-02-24 00:04 UTC
Labels: enhancement
